version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001"
    volumes:
      - ./src:/usr/src/app/src
    environment:
      - NODE_ENV=production
