version: "3"
services:
  react:
    image: shakeeb2001/crystal-cascade-frontend
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
  server:
    image: shakeeb2001/crystal-cascade-backend
    ports:
      - "3001:3001"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
