version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "3001"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3000"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - NODE_ENV=production
