version: "3"
services:
  react:
    image: react
    stdin_open: true
    ports: 
      - "3000:000"
    networks:
      - mern-app
  server:
    image: server
    ports:
      - "3001:3001"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
