version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - NODE_ENV=production
