version: '3'
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "3001"
    volumes:
      - ./Backend:/usr/src/app
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./Brontend
      dockerfile: Dockerfile
    ports:
      - "3000"
    volumes:
      - ./Frontend:/usr/src/app
    environment:
      - NODE_ENV=production
